language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH="master"
  - SOURCE_DIR="dist"
  - TARGET_BRANCH="gh-pages"
  - SSH_KEY="id_rsa"
  - GIT_NAME="gh-pages-travis"
  - GIT_EMAIL="deploy@travis-ci.org"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
branches:
  except:
  - gh-pages
before_install:
- openssl aes-256-cbc -K $encrypted_d5e0c5c779f2_key -iv $encrypted_d5e0c5c779f2_iv
  -in id_rsa.enc -out id_rsa -d
install:
- npm install
- npm run build
after_success:
- npm run gh-pages-travis
